/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApprovalButtonGroup: typeof import('./../components/ApprovalButtonGroup/ApprovalButtonGroup.vue')['default']
    ApprovalDescCard: typeof import('./../components/ApprovalDescCard/ApprovalDescCard.vue')['default']
    ApprovalDescList: typeof import('./../components/DescList/ApprovalDescList.vue')['default']
    AuthBackground: typeof import('./../components/AuthBackground.vue')['default']
    DescCard: typeof import('./../components/DescCard/DescCard.vue')['default']
    DescItemList: typeof import('./../components/DescItemList/DescItemList.vue')['default']
    DescList: typeof import('./../components/DescList/DescList.vue')['default']
    FileList: typeof import('./../components/FileList/FileList.vue')['default']
    Process: typeof import('./../components/Process/Process.vue')['default']
  }
}
